name: Deploy Simple

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Ambil Kodingan
      uses: actions/checkout@v3

    - name: Login Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}

    - name: Build & Push
      run: |
        IMAGE_TAG=${{ secrets.DOCKER_USER }}/irondeploy-final:${{ github.sha }}
        docker build -t $IMAGE_TAG .
        docker push $IMAGE_TAG

    - name: Deploy ke VPS
      run: |
        IMAGE_TAG=${{ secrets.DOCKER_USER }}/irondeploy-final:${{ github.sha }}
        
        # Hapus container lama
        docker stop iron-app || true
        docker rm iron-app || true
        
        # Jalankan container baru DENGAN LABEL MONITORING
        docker run -d \
          --name iron-app \
          -p 8080:80 \
          --restart always \
          --label app=iron-landing \
          $IMAGE_TAG